subprojects {

  plugins.withType(MavenPublishPlugin) {
	publishing {
	  repositories {
		maven {
		  name = "GitHubPackages"
		  url = uri("https://maven.pkg.github.com/${System.getenv("GITHUB_ACTOR")}/rsocket-broker-client")
		  credentials {
			username = project.findProperty("gpr.user")
			password = project.findProperty("gpr.key")
		  }
		}
	  }
	}

	tasks.named("publish").configure {
	  onlyIf { System.getenv('SKIP_RELEASE') != "true" }
	}
  }
}